### ISSUE TITLE
Can it be used with Android projects

### ISSUE THREAD

**Issue by iturki** [danshannon/javastravav3api#113]
Hi all,
I just tried using this lib on an Android app. I was faced with some dependency errors. I tried resolving them, but it seems that every time I resolve one a new one appear.
- Does the fact that javastravav is written on Java 8 has anything to do with this? I'm assuming Android SDK's are Java 7 dependent, but correct me if I'm wrong.
- Anyone uded javastravav on Android projects succesfully?

Thanks for the help!

**Comment by DCRichards** [comment]
Hi @iturki - you need to add this dependency to your app's `build.gradle` file, add the following to the dependencies section:

`compile 'com.github.danshannon:javastrava-api:1.0.1'`

I think you'll also need to make sure you have `mavenCentral()` in your allProjects repositories section of the top level Gradle file as well.

For future reference this is actually exactly the same as the Maven dependency that is given in the docs for this, but in Gradle we write these in the format <group>:<artifact>:<version>.

Hope this helps

**Comment by DCRichards** [comment]
Actually - @danshannon it would be great if this was mentioned in the docs for those not experienced with Gradle etc. Thanks for your work on this.

**Comment by DrOptix** [comment]
Because it is built using Java8 I'm not sure how much Android friendly it is.

Right now I'm trying to use it from an Android project, but the bugger  bugs me.

I'll try to build it with Java6

**Comment by DCRichards** [comment]
Yeah I realised that after I posted! Let us know if that works, I opted for writing my own API wrapped in the end!

**Comment by danshannon** [comment]
Definitely won't build in Java 6 (or 7 for that matter) as it uses the new concurrency libraries and is written using lambdas 

Sent from my iPhone

On 22 Jan 2016, at 9:01 AM, David Richards <notifications@github.com> wrote:

Yeah I realised that after I posted! Let us know if that works, I opted for writing my own API wrapped in the end!

**Comment by DrOptix** [comment]
Well I did not try it yet, but I have two ideas

- Create my own Kotlin wrapper for the Strava REST API
- Try and build JavaStrava with Java 1.8 and then try some black magic using retreolambda to try and convert the compiled classes to Java 1.6 bytecode.

If you ask me I think the first variant would be faster, especially if I don't need the full API implemented, for now. :)

**Comment by DCRichards** [comment]
It seems I didn't read the initial comment well enough, apologies! It would be great if there was an Android friendly version as this is an otherwise excellent library. When I have more time I'd be happy to have a crack at it, it seems @DrOptix might also be able to help, although rather him than me hacking around that bytecode ;-)

**Comment by danshannon** [comment]
Closing this in favour of #145
