### ISSUE TITLE
Some noob questions (token, authentication protocol, retrofit, javastrava, callback domain, reachable dataset)

### ISSUE THREAD

**Issue by eleagece** [danshannon/javastravav3api#114]
First of all: sorry if I shouldn't be posting this here. I'm new to github and javastrava. I didn't know where else to ask.

I'm trying to use javastrava to get access to Strava dataset. The point is that I just need data to process locally (for example I want to make some statistics and graphs) and I need no users authenticating into some web app. I already have My API Application page (https://www.strava.com/settings/api) with "Client ID", "Client Secret" and "Your Access Token (permisions: public)".  And now the questions:

1- With what shoud I fill "Authorization Callback Domain"? As I said I'm just making requests from my own computer in order to obtain data. I've read it should work with "localhost" but I'm not sure if that's true because now it is not working. It may sound silly but when it comes client-server stuff I'm a total noob.

2- About javastrava implementation and what the README says about connecting. I've tried the following:

```
Integer clientID=1234;  // the one i got in registration
String clientSecret="the-one-i-got-in-registration";
String accessToken="the-one-i-got-in-registration";
AuthorisationService service = new AuthorisationServiceImpl();
Token token = service.tokenExchange(clientID,clientSecret,accessToken);
```

But I get this error which I think it has something to do with the Callback Domain:

```
00:43:57.469 [main] WARN  javastrava.api.v3.rest.util.RetrofitErrorHandler - 400 Bad Request : StravaResponse [message=Bad Request, errors=[StravaAPIError [resource=RequestToken, field=code, code=invalid]]]
javastrava.api.v3.service.exception.BadRequestException: 400 Bad Request : StravaResponse [message=Bad Request, errors=[StravaAPIError [resource=RequestToken, field=code, code=invalid]]]
    at javastrava.api.v3.rest.util.RetrofitErrorHandler.handleError(RetrofitErrorHandler.java:113)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
    at com.sun.proxy.$Proxy16.tokenExchange(Unknown Source)
    at javastrava.api.v3.auth.impl.retrofit.AuthorisationServiceImpl.tokenExchange(AuthorisationServiceImpl.java:39)
    at Prueba.main(Prueba.java:16)
Caused by: retrofit.RetrofitError: 400 Bad Request
    at retrofit.RetrofitError.httpError(RetrofitError.java:40)
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    ... 3 more
```

3- Not about javastrava, but if anyone knows: can I access public activities from other athletes or just my own dataset?

Thank you in advance

**Comment by patoupatou** [comment]
I can't answer your question, but I'm having the same problem as you where I need to use the API with a bot (there will never be a user registration) and I'm having trouble simply doing that... I thought I could simply create a token with my application token but the constructor absolutely needs a TokenResponse...

**Comment by danshannon** [comment]
You need the authorisation code from Strava as described in the section on Token Exchange on this page: http://strava.github.io/api/v3/oauth/

What that means is that even though you're a bot, you still need to use OAuth to get a token (the javastrava test suite at https://github.com/danshannon/javastrava-test does that in test.utils.TestHttpUtils.getStravaAccessToken)
