### ISSUE TITLE
NumberFormatException: Expected an int but was 2258593636

### ISSUE THREAD

**Issue by bbuenz** [danshannon/javastravav3api#117]
I got this following exception when trying to pull a lap from Strava. It seems some ids don't fit in an integer and String or long would be a more appropriate type.
Here is the JSON causing this:

[{"id":2258593636,"resource_state":2,"name":"Lap 1","activity":{"id":743050589,"resource_state":1},"athlete":{"id":12017759,"resource_state":1},"elapsed_time":4359,"moving_time":4321,"start_date":"2016-10-13T00:41:49Z","start_date_local":"2016-10-12T17:41:49Z","distance":17120.8,"start_index":0,"end_index":848,"total_elevation_gain":316.0,"average_speed":3.9,"max_speed":5.0,"average_cadence":86.1,"average_heartrate":141.9,"max_heartrate":163.0,"lap_index":1}]

**Comment by danshannon** [comment]
Done
