### ISSUE TITLE
getActivity returns cached summary instead of detailed representation.

### ISSUE THREAD

**Issue by hobovsky** [danshannon/javastravav3api#119]
Hello Dan,

I run into following issue: first I list user activities with `listAuthenticatedAthleteActivities` or `listAllAuthenticatedAthleteActivities`, which return summary representations and put them in the activity cache. When I call `getActivity(id, true)` , I get the cached summary instead of detailed view.

To make things more difficult, calling `getActivity(id, true)` after `getActivity(id, false)` would also return unexpected results. Probably there also could happen that method expected to return a summary would return cached detailed representation, I am not sure if such scenario is possible with current set of methods.

Anyway, thank you very much for your work on **javastrava** library, it's a really great piece of software!

Best Regards,
    Maciek

**Comment by semteXKG** [comment]
Just wanted to open the issue myself. It really bites you when you expect the effort segments. I think one solution would be to mark the activity if it's "simple / important only / all" and update the cache entry accordingly. Is there something apparently wrong with that idea.

@danshannon I could provide a pull request in time if I could help you with that issue...

**Comment by danshannon** [comment]
This is a crappy bug - sorry that it's there!

In the mean time, a workaround is to disable the caching by setting jcs.default.cacheattributes.MaxObjects=0 in cache.ccf file (copy the sample-cache,ccf file to cache.ccf first, if you didn't already)

**Comment by danshannon** [comment]
Cache will now only store an object in cache if `getResourceState() == StravaResourceState.DETAILED`

**Comment by danshannon** [comment]
Should be fixed
