### ISSUE TITLE
401 Unauthorized while uploading an activity

### ISSUE THREAD

**Issue by Daszczu** [danshannon/javastravav3api#140]
Hello,
I've got 401 Unauthorized when I do strava.upload(...) with AuthorisationScope.WRITE.
I've got a Maven project and additionally I had to put my secrets and id in application.properties file. 
It wasn't enough just to put it in Java in tokenExchange(...) - that's weird for me.
Here's an example of my code and stacktrace:
![image](https://cloud.githubusercontent.com/assets/7733687/24071166/08264530-0bcc-11e7-80ad-85970e448bc3.png)

**Comment by danshannon** [comment]
@Daszczu can you give me rest of the text (off to the right of your second screenshot) after "401 Unauthorized : StravaResponse [" - that's the actual error message coming back from Strava and it should help working out what's wrong

**Comment by Daszczu** [comment]
The message is the same as the message above, that the AccessToken for field write_permission is missing.
It's the same json as on the top of console log.

**Comment by Daszczu** [comment]
Yeah, just as I thought. It was my fault. I didn't set the 'scope' to 'write' while requesting access token.
I've manually uploaded my activity and run the code again. 
There's the info about duplicate so it cannot be processed - that's cool, it's what I expected, but also there's a stack trace:
![image](https://cloud.githubusercontent.com/assets/7733687/24421407/6c21afac-13f6-11e7-89a7-f6501173c13d.png)

**Comment by danshannon** [comment]
I think that is normal behaviour - you uploaded a duplicate activity, and got a `400 Bad Request` error from the Strava API, which javastrava interprets as an `IllegalArgumentException` 

`400 Bad Request` errors are usually thrown because you specified an invalid value for one of the fields when doing a POST

**Comment by Daszczu** [comment]
Okay, so it's about me handling those exceptions then. 
Right now I also get "StravaServiceUnavailableException: 503 Service Unavailable: Back-end server is at capacity":
![image](https://cloud.githubusercontent.com/assets/7733687/24588046/471fdf2a-17c1-11e7-8572-89203599eb19.png)
but I know that this is from Strava and I'm going to handle it.
Thank you for your cooperation :)

**Comment by danshannon** [comment]
Yes the site was having issues last night
