### ISSUE TITLE
How to turn off printing to console (debug mode?)

### ISSUE THREAD

**Issue by Daszczu** [danshannon/javastravav3api#165]
Is there any way I could turn off printing to console?
When I upload an activity the content is printed on the console.
I've build a jar file which I execute and only want to get two results like 'OK' or 'Error" with the stacktrace.
Maybe there's a way to turn off the debug mode or something

**Comment by danshannon** [comment]
There is a way to do it - I'm at a conference today but I'll check it out

It's the retrofit logging so most likely somewhere in the log4j settings 

Sent from my iPhone

On 6 Apr 2017, at 4:36 am, Daszczu <notifications@github.com> wrote:

Is there any way I could turn off printing to console?
When I upload an activity the content is printed on the console.
I've build a jar file which I execute and only want to get two results like 'OK' or 'Error" with the stacktrace.
Maybe there's a way to turn off the debug mode or something

**Comment by danshannon** [comment]
There's a config.properties file (in latest versions, javastrava-config.properties)

In there you'll find a property: `retrofit.log_level=FULL`

If you set it to `retrofit.log_level=NONE` then there's no logging any more.

The code involved is in API.java in the `public static <T> T instance(final Class<T> class1, final Token token)` method where it invokes `RestAdapter.Builder()...setLogLevel()`

Hope this helps

Dan

**Comment by danshannon** [comment]
Should externalise the logging configuration to allow it to be managed by individual apps
