### ISSUE TITLE
Undocumented attribute kom_type in segment leaderboard

### ISSUE THREAD

**Issue by danshannon** [danshannon/javastravav3api#22]
There is an attribute `kom_type` returned by the segment leaderboard endpoint; this is undocumented!

**Comment by danshannon** [comment]
@paulmach Can you help out here - does this have specific meaning?

**Comment by paulmach** [comment]
That attribute is used internally when returning sets of leaderboards with an internal endpoint.  It will be nil, kom or year_kom.  External api users should already know which leaderboard type this is, since they requested it.
