### ISSUE TITLE
get segment effort - athlete_segment_stats.pr_date format inconsistent

### ISSUE THREAD

**Issue by danshannon** [danshannon/javastravav3api#28]
`HTTP GET https://www.strava.com/api/v3/segment_efforts/5591276015`

Returns `"athlete_segment_stats":{"effort_count":9,"pr_elapsed_time":48,"pr_date":"2015-01-06"}`

Date format is not consistent with other date formats returned by Strava API.

**Comment by paulmach** [comment]
This is a date as indicated by `pr_date`  and consistent with [iso 8601](http://en.wikipedia.org/wiki/ISO_8601)

**Comment by danshannon** [comment]
Examine using Java 8 java.time or Joda time to fix

**Comment by danshannon** [comment]
Use java.time.LocalDate and associated customer serialiser javastrava.json.impl.gson.serializer.LocalDateSerializer
