### ISSUE TITLE
Can't delete an activity with private=true

### ISSUE THREAD

**Issue by danshannon** [danshannon/javastravav3api#64]
`POST https://www.strava.com/api/v3/activities`
with body
```
{"name":"TO BE DELETED","description":"Created by Strava API v3 Java","distance":1000.1,"elapsed_time":1000,"type":"ride","start_date_local":"2015-03-25T02:13:28.018Z"}
```

followed by
`HTTP PUT https://www.strava.com/api/v3/activities/273369121`
with body
```
{"name":"Blah","type":"ride","private":true,"commute":true,"trainer":true,"gear_id":"b4689","description":"Blah"}
```

followed by 
`HTTP DELETE https://www.strava.com/api/v3/activities/273369121`

results in `401 Unauthorized`

**Comment by paulmach** [comment]
same, private token?

**Comment by danshannon** [comment]
Ahh... no that's where I've gone wrong, thinking that view_private was going to work a different way. Will fix at my end. Thanks @paulmach
