### ISSUE TITLE
Can't get my own efforts on my own private segment

### ISSUE THREAD

**Issue by danshannon** [danshannon/javastravav3api#65]
`HTTP GET https://www.strava.com/api/v3/segments/1190741/all_efforts?page=1&per_page=200`

which is a segment belonging to the authenticated user, gives a `404 Not Found` response

**Comment by paulmach** [comment]
Are you using a `view_private` token?

**Comment by danshannon** [comment]
No, my bad

**Comment by danshannon** [comment]
Caused by using a token without `view_private` scope
