### ISSUE TITLE
Introduce a StravaResourceState = PRIVATE

### ISSUE THREAD

**Issue by danshannon** [danshannon/javastravav3api#75]
This should solve a bunch of issues.

All service methods that return data that is private should return the data as an empty object with `resourceState = StravaResourceState.PRIVATE`

Retain the existing private flags on activity and segment

Checks for privacy should also check the token has NOT got `view_private` scope when dealing with `401 Unauthorised` - if it has this scope, then the unauthorised error is for some other reason.

My understanding of the basic rules:

1. Data that an athlete can flag as private includes: 
   * their own unredacted athlete info (including statistics),
   * activities (including laps, photos, zones, maps, streams, splits and achievements) flagged as private;
   * segments (including segment streams) flagged as private;
   * segment efforts (including streams) where the segment is private or the activity is private
1. **Data the authenticated athlete has flagged as private must not be returned** by the API unless the access token has `view_private` scope. In these circumstances javastrava will return an empty object with only the `id` and `resourceState = StravaResourceState.PRIVATE`
1. **Data the authenticated athlete has flagged as private must not be writable** unless the access token has `view_private` *and* `write` scopes. In these circumstances javastrava will throw an `UnauthorizedException`
1. **Data that another athlete has flagged as private must not be returned** by the API under any circumstances. In these circumstances javastrava will return an empty object with only the `id` and `resourceState = StravaResourceState.PRIVATE`
1. **ALL data belonging to another athlete** must not be writable under any circumstances (with the exception that it is OK to give kudos to, or comment on, an activity belonging to another user). In these circumstances javastrava will throw an `UnauthorizedException`

**Comment by danshannon** [comment]
Here are the rules:

Resource | Owned | Flagged Private | Exists | view_private | Result
----- | ----- | ----- | ----- | ----- | -----
Activity | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | Returned in full
Activity | :white_check_mark: | :white_check_mark: | :white_check_mark: | | PRIVATE
Activity | :white_check_mark: | :white_check_mark: | | :white_check_mark: | NULL
Activity | :white_check_mark: | :white_check_mark: | | | NULL
Activity | :white_check_mark: | | :white_check_mark: | :white_check_mark: | Returned in full
Activity | :white_check_mark: | | :white_check_mark: | | Returned in full
Activity | :white_check_mark: | | | :white_check_mark: | NULL
Activity | :white_check_mark: | | | | NULL
Activity | | :white_check_mark: | :white_check_mark: | :white_check_mark: | PRIVATE
Activity | | :white_check_mark: | :white_check_mark: | | PRIVATE
Activity | | :white_check_mark: | | :white_check_mark: | NULL
Activity | | :white_check_mark: | | | NULL
Activity | | | :white_check_mark: | :white_check_mark: | Returned in summary
Activity | | | :white_check_mark: | | Returned in summary
Activity | | | | :white_check_mark: | NULL
Activity | | | | | NULL

**Comment by danshannon** [comment]
Side effect is that invalid or revoked tokens will get PRIVATE objects all the time...

**Comment by danshannon** [comment]
Created branch issue75 to hold work on this issue

**Comment by paulmach** [comment]
When requesting using an invalid token I think you can use the json result `
{"message":"Authorization Error","errors":[{"resource":"Athlete","field":"access_token","code":"invalid"}]}` to determine if it's a token issue vs a privacy issue. For example, https://www.strava.com/api/v3/athlete

What is the other confusion, that sometimes we return 404 and sometimes 401? Yes, that is definitely confusing and it honestly looks like you know the most about it :)

**Comment by danshannon** [comment]
@paulmach Confusion isn't so much the difference between 404 and 401, more that the various API endpoints seem to return data that they shouldn't in some cases, but it's not consistent how they operate. Take a look at the top comment on this issue - that's my understanding of how `view_private` should interact with private flags on activities and segments, but the question is: is that how you at Strava intend it to work?

Thanks for your continuing assistance by the way, it really is appreciated at my end :)
