### ISSUE TITLE
500 server error listing all segment efforts

### ISSUE THREAD

**Issue by danshannon** [danshannon/javastravav3api#97]
`HTTP GET https://www.strava.com/api/v3/segments/1555421/all_efforts?page=81&per_page=200`

returns a `500 Internal Server Error`

**Comment by mathewbgordon** [comment]
I wasn't able to reproduce this one - do you have any more information?  Thanks!

**Comment by danshannon** [comment]
Still happening for me - 

`HTTP GET https://www.strava.com/api/v3/segments/1555421/all_efforts?page=81&per_page=200`

still returns 

`HTTP 500 https://www.strava.com/api/v3/segments/1555421/all_efforts?page=81&per_page=200`

(according to the logs at least)

I'm using a token which does _not_ have `view_private` or `write` scopes and attempting to list all the efforts on the segment - so

```
HTTP GET https://www.strava.com/api/v3/segments/1555421/all_efforts?page=1&per_page=200
HTTP GET https://www.strava.com/api/v3/segments/1555421/all_efforts?page=2&per_page=200
HTTP GET https://www.strava.com/api/v3/segments/1555421/all_efforts?page=3&per_page=200
...
HTTP GET https://www.strava.com/api/v3/segments/1555421/all_efforts?page=81&per_page=200
```

goes BANG!

**Comment by mathewbgordon** [comment]
Got it - it wasn't clear that it was only specifically page 81.  I can reproduce that, and pages 80 and 82 load just fine.  I'll poke around!
